spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/SEP
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
sep-front:
  url: http://localhost:5173/
